const { Pool } = require('pg');

let pool = null;

function getDatabaseUrl() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error('DATABASE_URL is required for PostgreSQL operations.');
  }
  return url;
}

function getPool() {
  if (pool) {
    return pool;
  }

  pool = new Pool({
    connectionString: getDatabaseUrl(),
    ssl: process.env.PG_SSL === 'true' ? { rejectUnauthorized: false } : false
  });

  return pool;
}

async function testConnection() {
  const pg = getPool();
  const result = await pg.query('SELECT NOW() AS now');
  return result.rows[0];
}

async function initSchema() {
  const pg = getPool();

  await pg.query(`
    CREATE TABLE IF NOT EXISTS tours (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      category TEXT DEFAULT 'LEO NÚI',
      location TEXT,
      duration TEXT,
      difficulty TEXT,
      description TEXT,
      image_url TEXT,
      image_urls TEXT,
      best_time TEXT,
      max_altitude TEXT,
      fixed_guest_count INTEGER DEFAULT 12,
      trip_details TEXT,
      notes_text TEXT,
      quote_text TEXT,
      price TEXT,
      itinerary_days TEXT,
      itinerary_day1 TEXT,
      itinerary_day2 TEXT,
      itinerary_day3 TEXT,
      includes_text TEXT,
      excludes_text TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS bookings (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tour_id INTEGER NOT NULL REFERENCES tours(id) ON DELETE CASCADE,
      start_date DATE NOT NULL,
      contact_name TEXT,
      contact_phone TEXT,
      contact_email TEXT,
      status TEXT DEFAULT 'pending',
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS booking_members (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      booking_id INTEGER NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      dob DATE,
      cccd TEXT,
      phone TEXT,
      address TEXT,
      medal INTEGER DEFAULT 0,
      medal_name TEXT,
      medical_condition INTEGER DEFAULT 0,
      medical_note TEXT,
      borrow_bag INTEGER DEFAULT 0,
      borrow_headlamp INTEGER DEFAULT 0,
      borrow_trekking_pole INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );
  `);
}

module.exports = {
  getPool,
  testConnection,
  initSchema
};
